name: CI with Snyk Code Analysis for Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-code:
    name: Snyk Code Analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Hoặc phiên bản JDK mà dự án sử dụng

      - name: Install Snyk CLI
        run: |
          curl -o snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/snyk

      # Authenticate with Snyk
      - name: Authenticate Snyk
        shell: bash
        run: snyk auth "aef3bc9e-2893-4fe2-946a-0a24928afa2d"

      # Run Snyk Code Scan
      - name: Run Snyk Code Scan
        run: snyk code test src/main/java --json-file-output=report.json
